# Generated by Django 4.2.6 on 2023-11-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_alter_cart_user_id'),
        ('Accounts', '0002_remove_user_phone_number_remove_user_reset_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
