# Generated by Django 4.2.6 on 2023-11-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
