# Generated by Django 4.2.7 on 2023-11-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_remove_product_discount_product_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='website',
            field=models.CharField(max_length=50),
        ),
    ]
