# Generated by Django 4.2.6 on 2023-11-01 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.user')),
            ],
        ),
    ]
