# Generated by Django 4.2.7 on 2023-11-05 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_product_image_alter_product_product_name'),
        ('Cart', '0003_remove_cart_quantity_remove_cart_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Accounts.product'),
        ),
    ]
