# Generated by Django 4.2.7 on 2023-11-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_product_image_alter_product_product_name'),
        ('Cart', '0005_alter_cart_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.ManyToManyField(default='1', to='Accounts.product'),
        ),
    ]
