# Generated by Django 4.2.7 on 2023-11-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_remove_cart_product_id_cart_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
